### ISSUE TITLE
Table doesn't update when file is reloaded or when new file is loaded

### ISSUE THREAD

**Issue by shaunwbell** [NOAA-PMEL/EcoFOCI_VisualEdit#22]
noted by @NOAA-Strausz - table can still be edited and saved properly but any reload feature still fails to update the table

**Comment by shaunwbell** [comment]
column highlighting doesn't change either

**Comment by NOAA-Strausz** [comment]
Ok the plots start at 0 depth but the grid starts at 1.  Threw me off there
for a min.

---------------
David Strausz
Physical Scientist Technician
NOAA FOCI-PMEL
7600 Sand Point Way N.E.
Seattle, WA 98115-6349
206-526-4510

**Comment by shaunwbell** [comment]
most recent commit update addresses
- column highlighting
- reloading files
- making entire columns missing
